### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by hemantso** [hemant-soni-vst-au4/POSITIONING-AND-FLOATING-ELEMENTS#1]

**Comment by ricardo123321** [comment]
don't forget to eliminate the button decoration from the banner and the comments

**Comment by ricardo123321** [comment]
kindly add resizability to the h1 and other elements of the page

**Comment by Cathella** [comment]
The header image is more to the left than the right. It should have the same margin

**Comment by ricardo123321** [comment]
the value break-word is deprecated don't forget to change it

**Comment by LoboArkano** [comment]
Consider use CSS instead of strong tag.

**Comment by ricardo123321** [comment]
on the css main-header h1

**Comment by hemantso** [comment]
thank you guys
